port 26379

sentinel resolve-hostnames yes

# sentinel monitor mymaster redis-master 6379 2 --> in local sentinel ip 172.18.0.3 for local testing docker is outside from our node application so we need to declare local ip 127.0.0.1
sentinel monitor mymaster 127.0.0.1 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000
sentinel parallel-syncs mymaster 1

protected-mode no